; タイムゾーン
date.timezone = "Asia/Tokyo"

; 文字コード
default_charset = "UTF-8"
mbstring.language = "Japanese"

; パフォーマンス
memory_limit = 512M
upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 300
